### ISSUE TITLE
项目无法运行

### ISSUE THREAD

**Issue by KonoSubazZ** [Chef5/PopRun-b#42]
您好，按照您的步骤起了一下项目，无法运行，想请教下您这是什么问题，以下是我的控制台报错

Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+DESKTOP-O49OUNT+2023-03-13+1616 to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-O49OUNT+2023-03-13+1616
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.
Tokens will be stored in plain text in "C:/Users/dark/AppData/Roaming/Composer/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth
Token (hidden):

**Comment by Chef5** [comment]
> 您好，按照您的步骤起了一下项目，无法运行，想请教下您这是什么问题，以下是我的控制台报错
> 
> Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+DESKTOP-O49OUNT+2023-03-13+1616 to retrieve a token. This token will have read-only permission for public information only. When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-O49OUNT+2023-03-13+1616 Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer. Tokens will be stored in plain text in "C:/Users/dark/AppData/Roaming/Composer/auth.json" for future use by Composer. For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth Token (hidden):

看样子是你无法克隆项目到本地，可以尝试下载zip， https://github.com/Chef5/PopRun-b/archive/refs/heads/master.zip
