### ISSUE TITLE
这个添加课程的时候显示有问题

### ISSUE THREAD

**Issue by kangnn** [Chef5/PopRun-b#43]
![%E)P978KNQ5XJKGTGNL(B6M](https://user-images.githubusercontent.com/77667172/229724521-5ef51e29-433a-45e4-9684-6a0540e1bb86.png)
初始化数据时打开网页显示{"isSuccess":false,"msg":"{\"errorInfo\":[\"23000\",1062,\"Duplicate entry 'lv0' for key 'r_honors.r_honors_desc_unique'\"]}","data":{"errorInfo":["23000",1062,"Duplicate entry 'lv0' for key 'r_honors.r_honors_desc_unique'"]}}

**Comment by Chef5** [comment]
第一次初始化数据时，网页显示空白，查看数据库中的表`r_honors `，`r_medals`中是否已经有数据了？有数据了就表示已经初始化完成，再次初始化数据就会报错`Duplicate entry ....`
